name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Add manual trigger

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Manual Approval
        if: github.event_name == 'workflow_dispatch'  # Only run on manual trigger
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Manually triggering workflow"

      - name: Build
        run: |
          # Your build commands here
          echo "Building..."

      - name: Deploy
        if: github.event_name != 'workflow_dispatch'  # Only run if not manually triggered
        run: |
          # Your deployment commands here
          echo "Deploying..."
